---
latex input: latex-support/first-header.tex
title: Introduction to the Study of Literature
instructor: Moacir P. de Sá Pereira
instructor url: http://moacir.com
instructor email: blah@blah.com
course url: http://moacir.com/courses-nyu/english-101-2017
course code: ENGL-UA 101.001
course term: Spring 2017
course room: ARC LL03
course time: MW 15:30–16:45
office hours: 244 Greene, 506, T 15:00–16:30
github url: http://github.com/muziejus/english-101-2017
transclude base: sections
base header level: 1
latex input: latex-support/second-header.tex
latex footer: latex-support/footer.tex
html header: <meta charset="utf-8" />
  <meta content="IE=edge" http-equiv="X-UA-Compatible" />
  <meta content="width=device-width, initial-scale=1" name="viewport" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!--[if IE]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> 
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
html footer: </div> <!--closes main container-fluid-->
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script>$('table').addClass("table table-hover");
    $('body').attr("data-offset", "70").attr("data-spy", "scroll").attr("data-target", "#navbarSpy").scrollspy({target: "#navbarSpy"});
    $('header').html("<h1>Introduction to the Study of Literature (English 101)</h1><p>Moacir P. de Sá Pereira (moacir at nyu)</p><p>Spring 2016, ARC LL03, MW 15:30–16:45</p><p>Office Hours: 244 Greene, 506, T 15:00–16:30</p>");
    $('#instructor').attr("href", "http://moacir.com").text("© 2016 Moacir P. de Sá Pereira");
    $('.navbar-brand').text("English 101");
    </script>



{{navbar.*}}

## Course description
{{course-description.md}}

## Goals of the course
{{goals.md}}

## Books
{{books.md}}

## Course requirements & policies

### Assessment
{{assessment.md}}

### Policies
{{policies.md}}

<!-- \newpage -->

## Schedule
{{schedule.md}}

<!-- \newpage -->

## Calendar
{{calendar.md}}


