---
latex input: syllabus-header
title: English 101
instructor: Moacir P. de Sá Pereira
transclude base: sections
base header level: 1
latex footer: syllabus-footer
bibtex: /Users/moacir/Dropbox/diss
html header: <meta charset="utf-8" />
  <meta content="IE=edge" http-equiv="X-UA-Compatible" />
  <meta content="width=device-width, initial-scale=1" name="viewport" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <meta content="Moacir P. de Sá Pereira" name="author" />
  <!--[if IE]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> 
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
html footer: <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


{{navbar.*}}

## Course description
{{course-description.md}}

## Goals of the course
{{goals.md}}

## Books (available at NYU BookCenter (hardcopies required)
{{books.md}}

## Course requirements & policies

### Assessment
{{assessment.md}}

### Policies
{{policies.md}}

<!-- \newpage -->

## Readings & classes schedule
{{schedule.md}}

<!-- \newpage -->

{{calendar.md}}
